#!/bin/bash

###
# Bash Beds Assessment
 
 # Using CSV file run analysis on bed census

 # Note: Make sure to give file execute permissions to run 
 #  $ chmod a+x <filename>

 # Note: To make it run:
 #  $ bash <filename>
###

# Access file

# Create subset of file for one location

# Provide answers to 4 questions


echo "St. Peter's Nursing And Rehabilitation Center reported this many censuses:"
grep "St. Peter's Nursing And Rehabilitation Center" -c beds.csv

echo "Earliest census was taken in:"
grep "St. Peter's Nursing And Rehabilitation Center" beds.csv | sort -ns | cut -d , -f 13 | tail -n 1

echo "Most recent census was taken in:"
grep "St. Peter's Nursing And Rehabilitation Center" beds.csv | sort -gs | cut -d , -f 13 | head -n 1

echo "The ten census dates with the lowest number of available beds for that nursing home in order are:"
grep "St. Peter's Nursing And Rehabilitation Center" beds.csv | sort -t, -k 17,17n | head -n 10 | cut -d ',' -f 13,17 |  tr ',' '\t'

echo "The ten census dates with the highest number of available beds for that nursing home in order are:"
grep "St. Peter's Nursing And Rehabilitation Center" beds.csv | sort -t, -k 17,17n | tail -n 10 | cut -d , -f 13,17 |  tr ',' '\t'
