#!/bin/bash

###
# Bash Beds Assessment
 
 # Using CSV file run analysis on bed census

 # Note: Make sure to give file execute permissions to run 
 #  $ chmod a+x <filename>

 # Note: To make it run:
 #  $ bash <filename>
###

echo "Please enter filename to run the assessment:"
read -a file_name

facility="St. Peter's Nursing And Rehabilitation Center"
result=results.txt

grep "$facility" -c $file_name | xargs -I % echo "$facility reported this many censuses: %" > $result

grep "$facility" $file_name | sort -ns | cut -d , -f 13 | tail -n 1 |xargs -I % echo echo "Earliest census was taken in: %" >> $result

grep "$facility" $file_name | sort -gs | cut -d , -f 13 | head -n 1 | xargs -I % echo "Most recent census was taken in: %" >> $result

echo "The ten census dates with the lowest number of available beds for that nursing home in order are:" >> $result
grep "$facility" $file_name | sort -t, -k 17,17n | head -n 10 | cut -d ',' -f 13,17 |  tr ',' '\t' >> $result

echo "The ten census dates with the highest number of available beds for that nursing home in order are:" >> $result
grep "$facility" $file_name | sort -t, -k 17,17n | tail -n 10 | cut -d , -f 13,17 |  tr ',' '\t' >> $result
